### PR TITLE
added bronze block and ingot

### PR DESCRIPTION
**Pull request by Thebestharrison1221**

### CODE REVIEW

**Comment by Rustypredator** [comment]
wasnt it Brass?  
Also should there be a recipe for a normal 9 ingots -> block recipe?  
Oh and idk but i guess for them to work in the recipes Red needs them in they need to be tagged right?  
Eh, well just check that in the game...  
I just checked the post, please change it to brass, then its good :+1:

**Review by Thebestharrison1221 — COMMENTED** [review]
fix v2

**Comment by Thebestharrison1221** [comment]
there we go

**Comment by Rustypredator** [comment]
Ok, looks good.
One question... Using the Pressing method, you use 4 Bronze to create 1 block. 
But just crafting you use 9 Bronze to create 1 block.  
what happens when you have the block? you cant just uncraft it right?  
If we want to add that uncrafting recipe, we will either change the pressing recipe to use 9 or the crafting to use 4, since there is only one block to uncraft from and we cant have it returning either 4 or 9 right? right.

**Comment by Thebestharrison1221** [comment]
there we go

**Pull request merged**
